repos:
  - repo: local
    hooks:
      - id: isort
        name: Running isort
        description: isort – library to sort imports alphabetically, and automatically separated into sections and by type
        entry: bash -c 'isort "$@"; git add -u' --
        language: python
        args: ["--filter-files"]
        files: \.py$
        always_run: true
      - id: autoflake
        name: Running autoflake
        description: autoflake – libarary to remove unused variables and imports
        entry: bash -c 'autoflake "$@"; git add -u' --
        language: python
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variables",
            "--expand-star-imports",
            "--ignore-init-module-imports",
          ]
        files: \.py$
        always_run: true
      - id: black
        name: Running black
        description: Black – uncompromising Python code formatter
        entry: bash -c 'black "$@"; git add -u' --
        language: python
        types: [python]
        args: ["--line-length=90"]
        always_run: true